version: "3.9"

services:
  app:
    container_name: invoiceshelf-app
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    restart: unless-stopped
    ports:
      - "${INVOICESHELF_HTTP_PORT:-8080}:8080"
    environment:
      APP_NAME: ${APP_NAME:-InvoiceShelf}
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost:8080}
      DB_CONNECTION: ${DB_CONNECTION:-sqlite}
      DB_DATABASE: ${DB_DATABASE:-/var/www/html/storage/app/database.sqlite}
      CACHE_STORE: ${CACHE_STORE:-file}
      SESSION_DRIVER: ${SESSION_DRIVER:-file}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-240}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-localhost}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS:-localhost:8080}
    volumes:
      - invoiceshelf_storage:/var/www/html/storage
      - invoiceshelf_cache:/var/www/html/bootstrap/cache

volumes:
  invoiceshelf_storage:
  invoiceshelf_cache:
