version: "3.9"

services:
  app:
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-invoiceshelf}
      DB_USERNAME: ${MYSQL_USER:-invoiceshelf}
      DB_PASSWORD: ${MYSQL_PASSWORD:-invoiceshelf}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: invoiceshelf-mysql
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-invoiceshelf}
      MYSQL_USER: ${MYSQL_USER:-invoiceshelf}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-invoiceshelf}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "${INVOICESHELF_MYSQL_PORT:-3306}:3306"
    volumes:
      - invoiceshelf_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  invoiceshelf_mysql:
